console.log(document.getElementById('age-table'))
console.log(document.querySelectorAll('#age-table label'))
console.log(document.querySelector('td'))
console.log(document.querySelector('form[name="search"]'))
console.log(document.querySelector('form input:first-Child'))
console.log(document.querySelector('form > input:last-Child'))